In [1]:
import duckdb as ddb
import pandas as pd

In [2]:
con = ddb.connect("../air_quality.db")

con

In [4]:
df = con.query("select * from raw.air_quality_data where parameter in ('so2', 'pm10', 'pm25')").to_df()

df.head()

,location_id,sensor_id,location,datetime,lat,lon,parameter,units,value,month,year,ingestion_datetime
0,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 00:45:00,22.627875,88.3804,pm10,µg/m³,64.87,05,2025,2025-11-15 22:20:06.804428
1,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:00:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-15 22:20:06.804428
2,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:15:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-15 22:20:06.804428
3,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:30:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-15 22:20:06.804428
4,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:45:00,22.627875,88.3804,pm10,µg/m³,56.89,05,2025,2025-11-15 22:20:06.804428

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15296 entries, 0 to 15295
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   location_id         15296 non-null  int64
 1   sensor_id           15296 non-null  int64
 2   location            15296 non-null  object
 3   datetime            15296 non-null  datetime64[us]
 4   lat                 15296 non-null  float64
 5   lon                 15296 non-null  float64
 6   parameter           15296 non-null  object
 7   units               15296 non-null  object
 8   value               15296 non-null  float64
 9   month               15296 non-null  object
 10  year                15296 non-null  int64
 11  ingestion_datetime  15296 non-null  datetime64[us]
dtypes: datetime64[us](2), float64(3), int64(3), object(4)
memory usage: 1.4+ MB

In [6]:
df.describe()

,location_id,sensor_id,datetime,lat,lon,value,year,ingestion_datetime
count,15296.0,1.529600e+04,15296,1.529600e+04,15296.0000,15296.000000,15296.0,15296
mean,3409320.0,1.223557e+07,2025-05-15 22:01:05.311192,2.262788e+01,88.3804,26.291067,2025.0,2025-11-16 22:04:45.740746
min,3409320.0,1.223556e+07,2025-05-01 00:45:00,2.262787e+01,88.3804,0.000000,2025.0,2025-11-15 22:20:06.804428
25%,3409320.0,1.223556e+07,2025-05-08 08:45:00,2.262787e+01,88.3804,9.060000,2025.0,2025-11-15 22:20:06.804428
50%,3409320.0,1.223556e+07,2025-05-15 15:22:30,2.262787e+01,88.3804,20.380000,2025.0,2025-11-16 22:04:45.740746
75%,3409320.0,1.223557e+07,2025-05-23 05:00:00,2.262787e+01,88.3804,35.790000,2025.0,2025-11-17 21:49:24.677065
max,3409320.0,1.223557e+07,2025-05-31 23:30:00,2.262787e+01,88.3804,548.460000,2025.0,2025-11-17 21:49:24.677065
std,0.0,1.247446e+00,NaN,3.552830e-15,0.0000,23.838166,0.0,NaN

In [7]:
df.describe(include='O')

,location,parameter,units,month
count,15296,15296,15296,15296
unique,1,3,2,1
top,"Rabindra Bharati University, Kolkata - WBPCB-3...",pm10,µg/m³,05
freq,15296,5104,10198,15296

In [8]:
df[df.duplicated(subset=["location_id", "parameter", "units", "value", "datetime"])]

,location_id,sensor_id,location,datetime,lat,lon,parameter,units,value,month,year,ingestion_datetime
7648,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 00:45:00,22.627875,88.3804,pm10,µg/m³,64.87,05,2025,2025-11-17 21:49:24.677065
7649,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:00:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-17 21:49:24.677065
7650,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:15:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-17 21:49:24.677065
7651,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:30:00,22.627875,88.3804,pm10,µg/m³,55.95,05,2025,2025-11-17 21:49:24.677065
7652,3409320,12235564,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-01 01:45:00,22.627875,88.3804,pm10,µg/m³,56.89,05,2025,2025-11-17 21:49:24.677065
...,...,...,...,...,...,...,...,...,...,...,...,...
15291,3409320,12235567,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-31 22:30:00,22.627875,88.3804,so2,ppb,7.33,05,2025,2025-11-17 21:49:24.677065
15292,3409320,12235567,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-31 22:45:00,22.627875,88.3804,so2,ppb,7.38,05,2025,2025-11-17 21:49:24.677065
15293,3409320,12235567,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-31 23:00:00,22.627875,88.3804,so2,ppb,7.12,05,2025,2025-11-17 21:49:24.677065
15294,3409320,12235567,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-31 23:15:00,22.627875,88.3804,so2,ppb,7.29,05,2025,2025-11-17 21:49:24.677065
15295,3409320,12235567,"Rabindra Bharati University, Kolkata - WBPCB-3...",2025-05-31 23:30:00,22.627875,88.3804,so2,ppb,6.44,05,2025,2025-11-17 21:49:24.677065

In [9]:
df.groupby(by="parameter", as_index=False).count()

,parameter,location_id,sensor_id,location,datetime,lat,lon,units,value,month,year,ingestion_datetime
0,pm10,5104,5104,5104,5104,5104,5104,5104,5104,5104,5104,5104
1,pm25,5094,5094,5094,5094,5094,5094,5094,5094,5094,5094,5094
2,so2,5098,5098,5098,5098,5098,5098,5098,5098,5098,5098,5098

In [10]:
df[df["value"] < 0]["location"].unique()

array([], dtype=object)

In [11]:
con.close()